name: flutter_to_mobilepay
description: Flutter plugin to integrate with MobilePay
version: 1.0.0
author: Andi Robin Halgren Semler <andirobinsemler@gmail.com>
homepage: https://github.com/semlette/flutter_to_mobilepay

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.andisemler.flutter_to_mobilepay
    pluginClass: FlutterToMobilepayPlugin
